#!/bin/sh
# Interactive Commitizen (Husky v9+ safe)

# Only trigger for normal commits (no -m, no merge)
if [ -z "$2" ]; then
  exec < /dev/tty
  npx cz --hook || true

  # If Commitizen filled the message file, stop Git from opening editor
  if [ -s "$1" ]; then
    exit 0
  fi
fi
# test